Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/08/2020
Var
// Seção de Declarações das variáveis 
n1:real
n2:real

Inicio
escreval ("sistema de inversão")
escreval ("-------------------")
escreval ()
escreva ("digite o primeiro numero")
       leia (n1)
escreva ("digite o segundo numero")
       leia (n2)
escreva (" esse numeros na inversão da ordem fica",n2,",",n1,"")


Fimalgoritmo