Algoritmo "repetidor"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Karolyne Ribeiro da Silva
// Data atual  : 10/08/2020
Var
// Seção de Declarações das variáveis 
nome: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval ("sistema de repetição")
escreval ("--------------------")
repita
   escreval("proa 4.0")
   nome <- nome+1
ate (nome = 1000)



Fimalgoritmo
