Algoritmo "vetor 1 e 2 somando no 3"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/08/2020
Var

n: vetor [1..3] de inteiro
ct : inteiro
Inicio

para ct de 1 ate 2 passo 1  faca
     escreval ("qual o numero ?")
       leia (N[ct])
n[3] <- n[1]+n[2]
       
fimpara
escreval ("o resultado dos numeros é:", n[3])


Fimalgoritmo